version: "2.4"

# Note: this file is mainly used for tests. If you want to run Superdesk or its
# services from docker, please use docker-compose.yml found in main Superdesk
# repository (https://github.com/superdesk/superdesk)

services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        ports:
            - "9200:9200"
        environment:
            - discovery.type=single-node
        tmpfs:
            - /usr/share/elasticsearch/data

    redis:
        image: redis:3
        ports:
            - "6379:6379"

    mongo:
        image: mongo:3.4
        ports:
            - "27017:27017"
        tmpfs:
            - /data/db

